### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [hamzatamry/kalah-game#1]
Hi. I am starting to learn C programming with SDL and found your project while looking for easy simplified examples to learn from. Would you consider adding a permissive license to your project, to allow learning from the code you created, so I (and others) can maybe use similar algorithms to yours in our projects?

**Comment by hamzatamry** [comment]
I've added a permissive license to my project, If you need anything regarding the project let me know.

ENJOY :)

**Comment by LifeCANvs** [comment]
Thank you so much for adding the MIT license, allowing anyone to learn from your work, and build upon it!

Also, thanks for your kind offer of support :)
